general {
    lock_cmd = pidof hyprlock || hyprlock
    # This turns off the screen right before the PC falls asleep
    before_sleep_cmd = hyprctl dispatch dpms off && loginctl lock-session
    # This turns the screen back on right after waking up
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
}

# Prevent system suspend/sleep flags when Moonlight streaming is engaged
listener {
    pidof = moonlight-qt
    on-timeout = echo "Moonlight active, bypassing standby rail"
}

listener {
    pidof = moonlight
    on-timeout = echo "Moonlight Flatpak active, bypassing standby rail"
}
