output "Samsung Electric Company C49RG9x H1AK500000" {
    mode 5120x1440@59.98
    scale 1.0
    alias $ultrawide
}

output "Dell Inc. DELL U2715H 0x30505353" {
    mode 2560x1440@59.95
    scale 1.0
    alias $vertical
}

output "Sharp Corporation 0x14D0 Unknown" {
    mode preferred
    scale 2.0
    alias $laptop
}

profile desktop-all {
    output $ultrawide position 0,0
    output $vertical position 5120,0 transform 270
    output $laptop position -1920,0

    exec ~/.config/hypr/scripts/workspaces.sh
}

profile desktop {
    output $ultrawide position 0,0
    output $vertical position 5120,0 transform 270
    exec ~/.config/hypr/scripts/workspaces.sh
}

profile laptop {
    output $ultrawide position 0,0

    exec ~/.config/hypr/scripts/workspaces.sh
}

profile laptop-dell {
    output $laptop position 0,0 
    output $vertical position 1920,0 transform 270

    exec ~/.config/hypr/scripts/workspaces.sh
}

profile laptop-ultrawide {
    output $ultrawide position 0,0
    output $laptop position -1920,0

    exec ~/.config/hypr/scripts/workspaces.sh
}
